# Configuração do servidor Nginx
server {
  # Ouve na porta 80
  listen 80;

  # Define a raiz onde os arquivos do site estão localizados
  root /usr/share/nginx/html;

  # Define o arquivo de índice principal
  index index.html;

  # Configuração para qualquer localização/rota
  location / {
    # Tenta encontrar o arquivo correspondente ao URI solicitado.
    # Se não encontrar, tenta como um diretório.
    # Se ambas as tentativas falharem, ele redireciona para /index.html.
    # Isso é o que faz o roteamento de uma SPA funcionar.
    try_files $uri $uri/ /index.html;
  }
}
